//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForms2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Edu_Id { get; set; }
        public string Degree { get; set; }
        public string Course { get; set; }
        public string Program_course { get; set; }
        public string Elective { get; set; }
        public string CollegeName { get; set; }
        public string UniversityName { get; set; }
        public Nullable<System.DateTime> fromYear { get; set; }
        public Nullable<System.DateTime> Toyear { get; set; }
        public Nullable<int> percentageYear { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public Nullable<int> self_Id_fk { get; set; }
    
        public virtual selfInformation selfInformation { get; set; }
    }
}
