//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForms2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiance
    {
        public int Exp_Id { get; set; }
        public string CompanyName1 { get; set; }
        public Nullable<System.DateTime> YearOF1 { get; set; }
        public string Position1 { get; set; }
        public string CompanyName2 { get; set; }
        public Nullable<System.DateTime> YearOF2 { get; set; }
        public string Position2 { get; set; }
        public string CompanyName3 { get; set; }
        public Nullable<System.DateTime> YearOF3 { get; set; }
        public string Position3 { get; set; }
        public Nullable<int> self_Id_fk_fk { get; set; }
    
        public virtual selfInformation selfInformation { get; set; }
    }
}
