//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForms2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public int Gnder_ID { get; set; }
        public string Gender1 { get; set; }
        public Nullable<int> selfe_Id { get; set; }
    
        public virtual selfInformation selfInformation { get; set; }
    }
}
