//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForms2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int L_Id { get; set; }
        public string Language1 { get; set; }
        public Nullable<bool> read1 { get; set; }
        public Nullable<bool> write1 { get; set; }
        public Nullable<bool> speak1 { get; set; }
        public Nullable<bool> understand1 { get; set; }
        public string Language2 { get; set; }
        public Nullable<bool> read2 { get; set; }
        public Nullable<bool> write2 { get; set; }
        public Nullable<bool> speak2 { get; set; }
        public Nullable<bool> understand2 { get; set; }
        public string Language3 { get; set; }
        public Nullable<bool> read3 { get; set; }
        public Nullable<bool> write3 { get; set; }
        public Nullable<bool> speak3 { get; set; }
        public Nullable<bool> understand3 { get; set; }
        public string Language4 { get; set; }
        public Nullable<bool> read4 { get; set; }
        public Nullable<bool> write4 { get; set; }
        public Nullable<bool> speak4 { get; set; }
        public Nullable<bool> understand4 { get; set; }
        public Nullable<int> self_FK { get; set; }
    
        public virtual selfInformation selfInformation { get; set; }
    }
}
