//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForms2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selfInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public selfInformation()
        {
            this.Educations = new HashSet<Education>();
            this.Experiances = new HashSet<Experiance>();
            this.Genders = new HashSet<Gender>();
            this.Languages = new HashSet<Language>();
        }
    
        public int self_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddileName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> PhoneNumber2 { get; set; }
        public string Email { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAdress { get; set; }
        
        public string Gender1 { get; set; }
        public string Language1 { get; set; }
        public Nullable<bool> read1 { get; set; }
        public Nullable<bool> write1 { get; set; }
        public Nullable<bool> speak1 { get; set; }
        public Nullable<bool> understand1 { get; set; }
        public string Language2 { get; set; }
        public Nullable<bool> read2 { get; set; }
        public Nullable<bool> write2 { get; set; }
        public Nullable<bool> speak2 { get; set; }
        public Nullable<bool> understand2 { get; set; }
        public string Language3 { get; set; }
        public Nullable<bool> read3 { get; set; }
        public Nullable<bool> write3 { get; set; }
        public Nullable<bool> speak3 { get; set; }
        public Nullable<bool> understand3 { get; set; }
        public string Language4 { get; set; }
        public Nullable<bool> read4 { get; set; }
        public Nullable<bool> write4 { get; set; }
        public Nullable<bool> speak4 { get; set; }
        public Nullable<bool> understand4 { get; set; }
        public string Degree { get; set; }
        public string Course { get; set; }
        public string Program_course { get; set; }
        public string Elective { get; set; }
        public string CollegeName { get; set; }
        public string UniversityName { get; set; }
        public Nullable<System.DateTime> fromYear { get; set; }
        public Nullable<System.DateTime> Toyear { get; set; }
        public Nullable<int> percentageYear { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string CompanyName1 { get; set; }
        public Nullable<System.DateTime> YearOF1 { get; set; }
        public string Position1 { get; set; }
        public string CompanyName2 { get; set; }
        public Nullable<System.DateTime> YearOF2 { get; set; }
        public string Position2 { get; set; }
        public string CompanyName3 { get; set; }
        public Nullable<System.DateTime> YearOF3 { get; set; }
        public string Position3 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experiance> Experiances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gender> Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Languages { get; set; }
    }
}
